[package]
name = "krabkrab_infra"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Infrastructure helpers for KrabKrab"

[dependencies]
krabkrab_common = { path = "../common" }
